### ISSUE TITLE
Could not find a declaration file for module 'react-paginating'.

### ISSUE THREAD

**Issue by nickwild-999** [ChoTotOSS/react-paginating#1]
Hi,

When I NPM install I get the above error. I am using Gatsby.
Any ideas?

Many thanks

Nick

**Comment by davidnguyen179** [comment]
This issue happened when the package does not have the declaration file for `typescript` support. Currently, I don't support the declaration for typescript yet. I will support for the next version. Thanks for report.

**Comment by davidnguyen179** [comment]
Hi @nickwild-999 

You could try again with a new version. I published a new package with `typescript` support.
