### ISSUE TITLE
Example using React Hooks

### ISSUE THREAD

**Issue by dongepulango** [ChoTotOSS/react-paginating#43]
Hi, I'm new to React and I would like to use this component as a Hook instead of normal Class. Is there a working example I can view?

Thanks

**Comment by davidnguyen179** [comment]
This component already applied `hook` itself. You just need to install `react-paginating@1.3.0-hook.1` and use it.

You could check the source code to see how I applied hook.
**Code**
https://github.com/ChoTotOSS/react-paginating/blob/hook/src/Pagination/Pagination.js

**Comment by dongepulango** [comment]
Thanks
