### ISSUE TITLE
Question - Is the composant compatible with IE 11 ?

### ISSUE THREAD

**Issue by ChristPetitjean** [ChoTotOSS/react-paginating#70]
Hello there,

A relative simple question: Is it compatible with IE 11 ?

Kind Regards.

**Comment by davidnguyen179** [comment]
The version `1.3.1` is using react 16 and not sure whether it supports IE 11 or not. But to be safe, you can use version https://github.com/ChoTotOSS/react-paginating/releases/tag/1.2.1 => this one is using react 15

**Comment by ChristPetitjean** [comment]
Just tested and same issue. It found a sytax error. I think it's related to babel transpiler but not found yet the source.
