### ISSUE TITLE
How to send the event parameter onPageChange

### ISSUE THREAD

**Issue by AnoojNair** [ChoTotOSS/react-paginating#8]
Hi,

Are there any code samples which show how to send the click event parameter to the onPageChange? So that i can stop propagating it?

**Comment by davidnguyen179** [comment]
Hi there, I think the event has to have the event object as the param.

**Comment by AnoojNair** [comment]
Doesn't seem to work in firefox , looks like firefox handles events differently

**Comment by abusada** [comment]
i made [PR](https://github.com/ChoTotOSS/react-paginating/pull/10) to fix this @davidnguyen179
